# Generated by Django 2.2.3 on 2020-03-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=2)),
                ('nickname', models.CharField(max_length=50)),
                ('privilege', models.IntegerField()),
                ('photo', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homework_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('message', models.TextField(null=True)),
                ('release_time', models.DateTimeField()),
                ('deadline_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('checksum', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('scheduler_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('timezone_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('todolist_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('deadline_time', models.DateTimeField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Account')),
                ('homework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Homework')),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Scheduler')),
            ],
        ),
        migrations.CreateModel(
            name='Takeclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Account')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
            ],
        ),
        migrations.AddField(
            model_name='scheduler',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Timezone'),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
            ],
        ),
    ]
