# Generated by Django 3.0.3 on 2020-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200510_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
