# Generated by Django 3.0.3 on 2020-05-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_todolist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='account_id',
            new_name='account',
        ),
    ]
