# Generated by Django 3.0.3 on 2020-05-31 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200527_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='scheduler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Scheduler'),
        ),
    ]
