# Generated by Django 3.0.4 on 2020-06-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200531_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.CharField(default="require('../../assets/images/user/user0.png')", max_length=50),
        ),
    ]
