# Generated by Django 3.0.4 on 2020-06-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200613_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
