# Generated by Django 3.0.4 on 2020-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200613_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.CharField(default='/static/img/user0.png', max_length=50),
        ),
    ]
