def get_course_sample_data():
    ret = {1: {'lesson': [{'name': '并发理论', 'index': 1},
                          {'name': '算法设计与分析', 'index': 2},
                          {'name': '计算机体系结构', 'index': 3},
                          {'name': '软件工程', 'index': 4}]},
           2: {'lesson': [{'name': '华语电影评析', 'index': 1},
                          {'name': '概率论与数理统计', 'index': 2},
                          {'name': '信息安全原理', 'index': 3},
                          {'name': '操作系统', 'index': 4},
                          {'name': '计算机网络', 'index': 5},
                          {'name': '自然语言处理', 'index': 6},
                          {'name': '学术英语（科学技术）', 'index': 7}]},
           3: {'lesson': [
               {'name': '代数结构与数理逻辑', 'index': 1},
               {'name': '数据库引论', 'index': 2},
               {'name': '模式识别与机器学习', 'index': 3},
               {'name': '计算机系统基础（下）', 'index': 4},
               {'name': '数据挖掘技术', 'index': 5},
               {'name': '英语论说文写作', 'index': 6},
               {'name': '排球', 'index': 7},
               {'name': '《理想国》导读', 'index': 8},
               {'name': '应用伦理学', 'index': 9},
               {'name': '形势与政策IV', 'index': 10}]},
           4: {'lesson': [{'name': '概率论与数理统计', 'index': 1},
                          {'name': '微观经济学', 'index': 2},
                          {'name': '会计学', 'index': 3},
                          {'name': '数字逻辑与部件设计', 'index': 4},
                          {'name': '数字逻辑与部件设计实验', 'index': 5},
                          {'name': '数据结构', 'index': 6},
                          {'name': '计算机系统基础（上）', 'index': 7},
                          {'name': '集合与图论', 'index': 8},
                          {'name': '排球', 'index': 9},
                          {'name': '形势与政策III', 'index': 10}, {
                              'name': '毛泽东思想和中国特色社会主义理论体系概论A',
                              'index': 11}, {
                              'name': '毛泽东思想和中国特色社会主义理论体系概论B',
                              'index': 12}]},
           5: {'lesson': [{'name': '面向对象程序设计', 'index': 1},
                          {'name': '英语视听', 'index': 2},
                          {'name': '模拟电子学基础', 'index': 3},
                          {'name': '数学分析BII', 'index': 4},
                          {'name': '军事理论', 'index': 5},
                          {'name': '网球', 'index': 6},
                          {'name': '大学物理B(下) ', 'index': 7},
                          {'name': '基础物理实验', 'index': 8},
                          {'name': '中国近现代史纲要', 'index': 9},
                          {'name': '形势与政策II', 'index': 10}]},
           }
    return ret
